[package]
name = "renderer"
version = "0.1.0"
authors = ["Hassan Farooq <hfarooq@tenstorrent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.10.2"
num = "0.2.1"
